#%RAML 1.0 NamedExample
value:
  -
    alertID: 221
    subscriptionID: 111
    delayedMinute: 00:30:10
    delayType: DELAYED
    DelayReason: This Train is Delayed due to speed regulations
    alertStatus: SUCCESS
    createdTimestamp: 2021-03-11T09:26:12
  -
    alertID: 222
    subscriptionID: 112
    delayedMinute: 00:30:15
    delayType: CANCELLED
    DelayReason: This Train is Cancelled due to Heavy Traffic
    alertStatus: SUCCESS
    createdTimestamp: 2021-03-14T10:25:19
  -
    alertID: 223
    subscriptionID: 113
    delayedMinute: 00:30:17
    delayType: DELAYED
    DelayReason: This Train is Delayed due to Heavy Traffic
    alertStatus: SUCCESS
    createdTimestamp: 2021-03-14T10:45:20