#%RAML 1.0 NamedExample
value:
  -
    subscriptionID?: 111
    userID: 00g0MGHGPnYrcOaP17H
    sourceLocation: OXFORD
    destinationLocation: WESTMINSTER
    fromTime: 09:36:21
    toTime: 10:36:25
    alertTimePeriod: 00:30:00
    createdTimestamp: 2021-03-11T09:17:26
    updatedTimestamp: 2021-03-12T09:11:20
  -
    subscriptionID?: 112
    userID: 00g0MGHGPnYrcOaP17H
    sourceLocation: OXFORD
    destinationLocation: LONDON BRIDGE
    fromTime: 09:36:21
    toTime: 10:36:25
    alertTimePeriod: 00:30:00
    createdTimestamp: 2021-03-11T09:17:26
    updatedTimestamp: 2021-03-12T09:11:20
  -
    subscriptionID?: 113
    userID: 00g0MGHGPnYrcOaP17H
    sourceLocation: OXFORD
    destinationLocation: WATERLOO
    fromTime: 09:36:21
    toTime: 10:36:25
    alertTimePeriod: 00:30:00
    createdTimestamp: 2021-03-11T09:17:26
    updatedTimestamp: 2021-03-12T09:11:20
