#%RAML 1.0 NamedExample
value:
  alertID?: 221
  subscriptionID: 111
  delayedMinute: 00:30:10
  delayType: DELAYED
  DelayReason: This Train is Delayed due to speed regulations
  alertStatus: SUCCESS
  createdTimestamp: 2021-03-11T09:26:12
  